// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTOwinPWpPoBwNsHr9227u1gd2tNt1Ad0',
    appId: '1:797915697768:web:f44bdc910843bf28c6e1dd',
    messagingSenderId: '797915697768',
    projectId: 'quizverse-v2',
    authDomain: 'quizverse-v2.firebaseapp.com',
    storageBucket: 'quizverse-v2.firebasestorage.app',
    measurementId: 'G-Q1W0ES32PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM1Fkcn_qeRW8CNu8QhHF-knQ1-jHzP-w',
    appId: '1:797915697768:android:093f2d181f3a9efec6e1dd',
    messagingSenderId: '797915697768',
    projectId: 'quizverse-v2',
    storageBucket: 'quizverse-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAehg2oB_FGfra2liv17JDbdvJAv_F1lu4',
    appId: '1:797915697768:ios:861daa875df38987c6e1dd',
    messagingSenderId: '797915697768',
    projectId: 'quizverse-v2',
    storageBucket: 'quizverse-v2.firebasestorage.app',
    iosBundleId: 'com.example.quizverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAehg2oB_FGfra2liv17JDbdvJAv_F1lu4',
    appId: '1:797915697768:ios:861daa875df38987c6e1dd',
    messagingSenderId: '797915697768',
    projectId: 'quizverse-v2',
    storageBucket: 'quizverse-v2.firebasestorage.app',
    iosBundleId: 'com.example.quizverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTOwinPWpPoBwNsHr9227u1gd2tNt1Ad0',
    appId: '1:797915697768:web:0126eae1a0d55cd9c6e1dd',
    messagingSenderId: '797915697768',
    projectId: 'quizverse-v2',
    authDomain: 'quizverse-v2.firebaseapp.com',
    storageBucket: 'quizverse-v2.firebasestorage.app',
    measurementId: 'G-J3TGRX0KFY',
  );
}
